name: glass_shop
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  rive: ^0.7.22
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  
 

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/Fonts/Comfortaa-Regular.ttf
        - asset: assets/Fonts/Comfortaa-Bold.ttf
        - asset: assets/Fonts/Comfortaa-Light.ttf
  